# Generated by Django 3.2.7 on 2021-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDonaite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coat', models.CharField(choices=[('1', '500'), ('2', '1000'), ('3', '1500')], max_length=10, verbose_name='Сумма')),
                ('way_of_writing', models.CharField(blank=True, choices=[('м', 'Каждый месяц'), ('к', 'Каждый квартал')], max_length=10, verbose_name='Способ спесания')),
                ('pib', models.CharField(max_length=255, verbose_name='П.I.Б')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
        ),
    ]
