# Generated by Django 3.2.7 on 2021-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='news/images/')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('choiseTypeNews', models.CharField(choices=[('Н', 'Новости'), ('У', 'Истории успеха'), ('Б', 'Блог')], max_length=1, verbose_name='Тип Новостей')),
            ],
        ),
    ]
