# Generated by Django 3.2.7 on 2021-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ на вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altPhoto', models.CharField(max_length=255, verbose_name='Описание фото')),
                ('photo', models.ImageField(upload_to='about_us/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStatus', models.CharField(max_length=255, verbose_name='Название статуса')),
                ('logo', models.ImageField(upload_to='about_us/logoStatus/', verbose_name='Логотип')),
                ('description', models.TextField(verbose_name='Описания цели')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOfHebron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('image', models.ImageField(upload_to='about_us/photoTeam/')),
                ('post', models.TextField(verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='about_us/video/')),
            ],
        ),
    ]
