# Generated by Django 3.2.7 on 2021-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210927_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfDonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='headerPage/logo/')),
            ],
        ),
        migrations.DeleteModel(
            name='New',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verific_password',
            new_name='verificPassword',
        ),
    ]
